# prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['apple-production-kstarid.up.railway.app'] 
