global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "apple_quality_model"
    static_configs:
      - targets: ["localhost:8501"]
    metrics_path: "/metrics"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
